// sexo, edad, item
import 'package:flutter/material.dart';
import 'package:precarina/l10n/app_localizations.dart';

enum Genero {
  femenino,
  masculino,
}

enum Edad {
  cincoAocho,
  nueveAtrece,
  catorceAdieciocho,
}

enum Items {
  vegetalesVerdes,
  vegetalesRojos,
  legumbres,
  tuberculos,
  otrosVegetales,
  frutas,
  pan,
  pastasIntegrales,
  pastasRefinadas,
  lacteos,
  quesos,
  carnes,
  pescados,
  semillas,
  aceites,
}

List<String> getTitulos(BuildContext context) {
  final l10n = AppLocalizations.of(context)!;
  return [
    l10n.txtVegetalesVerdes,
    l10n.txtVegetalesRojosNaranjas,
    l10n.txtLegumbres,
    l10n.txtTuberculosPapaBatataMandioca,
    l10n.txtOtrosVegetales,
    l10n.txtFrutas,
    l10n.txtPan,
    l10n.txtPastasYMasaIntegrales,
    l10n.txtPastasYMasaRefinadasNoIntegrales,
    l10n.txtLacteosLecheYogurParcialmenteDescremados,
    l10n.txtQuesosSemidescremadosUntablesOSemiSolidos,
    l10n.txtCarnesRojasAveYHuevoPorDia,
    l10n.txtPescados,
    l10n.txtFrutosSecosYSemillas,
    l10n.txtAceites
  ];
}

List<List<List<List<String>>>> getOpciones(BuildContext context) {
  final l10n = AppLocalizations.of(context)!;
  return [
// femenino
    [
// Cinco a ocho
      [
// green vegetables
        [
          l10n.txtOnePlatePerWeek,
          l10n.txtHalfPlatePerWeek,
          l10n.txtLessThanHalfPlatePerWeek,
        ],
        [
          l10n.txtThreePlatesPerWeekOrOneSmallUnitDaily,
          l10n.txtOnePlatePerWeek,
          l10n.txtLessThanOnePlatePerWeek,
        ],
        [
          l10n.txtHalfPlatePerWeekOrTwoSmallMedallionsPerWeek,
          l10n.txtQuarterPlatePerWeekOrOneSmallMedallionPerWeek,
          l10n.txtLessThanQuarterPlatePerWeekOrLessThanOneSmallMedallionPerWeek,
        ],
        [
          l10n.txtHalfSmallUnitDailyOrQuarterPlateDailyOrThreeSmallUnitsPerWeek,
          l10n.txtOneSmallUnitDailyOrHalfPlateDailyOrThreeMediumUnitsPerWeek,
          l10n.txtMoreThanOneSmallUnitDailyOrMoreThanHalfPlateDailyOrMoreThanThreeMediumUnitsPerWeek,
        ],
        [
          l10n.txtThreeMediumUnitsPerWeekOrOneThirdRawPlateDailyOrOneFourthCookedPlateDaily,
          l10n.txtOneMediumUnitPerWeekOrOneFourthRawPlateDailyOrOneFourthCookedPlateFourTimesPerWeek,
          l10n.txtLessThanOneMediumUnitPerWeekOrLessThanOneFourthRawPlateDailyOrLessThanOneFourthCookedPlateFourTimesPerWeek,
        ],
        [
          l10n.txtOneMediumUnitDailyOrTwoSmallUnitsDaily,
          l10n.txtOneSmallUnitDaily,
          l10n.txtLessThanOneSmallUnitDaily,
        ],
        [
          l10n.txtOneSliceOfBreadOrOneSmallMignonOrThreeWaterCrackers,
          l10n.txtTwoSlicesOfSandBreadOrTwoSmallMignonsOrSixWaterCrackers,
          l10n.txtMoreThanTwoSlicesOfSandBreadOrMoreThanTwoSmallMignonsOrMoreThanSixWaterCrackers,
        ],
        [
          l10n.txtQuarterPlateDailyOrOneServingOfDoughDaily,
          l10n.txtHalfPlateDailyOrTwoServingsOfDoughDaily,
          l10n.txtMoreThanHalfPlateDailyOrMoreThanTwoServingsOfDoughDaily,
        ],
        [
          l10n.txtQuarterPlateDailyOrOneServingOfDoughDaily,
          l10n.txtHalfPlatePerDayOrTwoServingsOfDough,
          l10n.txtMoreThanHalfPlatePerDayOrMoreThanTwoServingsOfDoughPerDay,
        ],
        [
          l10n.txtThreeQuartersCupBreakfastTypeDailyOrTwoCupsTeaTypeDaily,
          l10n.txtHalfCupBreakfastTypeDailyOrOneCupTeaTypeDaily,
          l10n.txtLessThanHalfCupBreakfastTypeDailyOrLessThanOneCupTeaTypeDaily,
        ],
        [
          l10n.txtOneServingTheSizeOfSmallMatchboxOrSizeOfHalfSUBECardOrTwoTableSpoons,
          l10n.txtHalfServingTheSizeOfSmallMatchboxOrOneDieOrOneTableSpoon,
          l10n.txtLessThanHalfServingTheSizeOfSmallMatchboxOrLessThanOneDieOrLessThanOneTableSpoon,
        ],
        [
          l10n.txtHalfMediumSteakPerDayOrOneAndHalfEggsDailyOrOneMediumMincedMeat,
          l10n.txtOneMediumSteakDailyOrUpToTwoEggUnitsDailyOrOneServingTheSizeOfSliceOfVealPlusOneEggDaily,
          l10n.txtMoreThanOneMediumSteakDailyOrMoreThanTwoEggUnitsDailyOrMoreThanOneServingTheSizeOfSliceOfVealPlusOneEggDaily,
        ],
        [
          l10n.txtOneMediumServingPerWeekOrOneCanPerWeek,
          l10n.txtOneSmallServingPerWeekOrHalfCanPerWeek,
          l10n.txtLessThanOneSmallServingPerWeekOrLessThanHalfCanPerWeek,
        ],
        [
          l10n.txtFourWalnutHalvesOrEightAlmondsOrOneTableSpoonOfSeedsOrPeanutsDaily,
          l10n.txtTwoWalnutHalvesOrFourAlmondsOrOneTeaspoonOfSeedsOrPeanutsDaily,
          l10n.txtLessThanTwoWalnutHalvesOrLessThanFourAlmondsOrLessThanOneTeaspoonOfSeedsOrPeanutsDaily,
        ],
        [
          l10n.txtTwoTableSpoonsDessertTypeDaily,
          l10n.txtOneTableSpoonDessertTypeDaily,
          l10n.txtLessThanOneTableSpoonDessertTypeDaily,
        ],
      ], //Fin 5 a 8 años
// 9 a 13 años
      [
        [
          l10n.txtOneAndHalfPlatePerWeek,
          l10n.txtOnePlatePerWeek,
          l10n.txtLessThanOnePlatePerWeek,
        ],
        [
          l10n.txtFourPlatesPerWeek,
          l10n.txtTwoPlatesPerWeek,
          l10n.txtLessThanTwoPlatesPerWeek,
        ],
        [
          l10n.txtOnePlatePerWeekOrHalfPlatePlusOneMedallionPerWeek,
          l10n.txtHalfPlatePerWeekOrQuarterPlatePlusOneMedallionPerWeek,
          l10n.txtLessThanHalfPlatePerWeekOrQuarterPlatePlusOneMedallionPerWeek,
        ],
        [
          l10n.txtOneThirdPlateDailyOrUpToThreeMediumUnitsPerWeek,
          l10n.txtHalfPlateOrUpToFiveSmallUnitsPerWeek,
          l10n.txtMoreThanHalfPlateOrMoreThanFiveSmallUnitsPerWeek,
        ],
        [
          l10n.txtFourMediumUnitsPerWeekOrHalfRawPlateDailyOrQuarterCookedPlateDaily,
          l10n.txtTwoMediumUnitsPerWeekOrQuarterPlateDaily,
          l10n.txtLessThanTwoMediumUnitsPerWeekOrQuarterPlateDaily,
        ],
        [
          l10n.txtOneAndHalfLargeUnitPerDayOrTwoMediumUnitsPerDay,
          l10n.txtOneMediumUnitPerDay,
          l10n.txtLessThanOneMediumUnitPerDay,
        ],
        [
          l10n.txtUpToTwoSlicesOfBreadPerDayOrTwoSmallMignonsOrSixWaterBiscuits,
          l10n.txtThreeSlicesOfBreadPerDayOrThreeSmallMignonsOrNineWaterBiscuits,
          l10n.txtMoreThanThreeSlicesOfBreadPerDayOrMoreThanThreeSmallMignonsOrMoreThanNineWaterBiscuits,
        ],
        [
          l10n.txtQuarterPlateOfWholeWheatPastaPerDayOrOnePortionOfDough,
          l10n.txtHalfPlatePerDayOrTwoPortionsOfDough,
          l10n.txtMoreThanHalfPlatePerDayOrTwoPortionsOfDough,
        ],
        [
          l10n.txtQuarterPlateOfWholeWheatPastaPerDayOrOnePortionOfDough,
          l10n.txtHalfPlatePerDayOrTwoPortionsOfDough,
          l10n.txtMoreThanHalfPlatePerDayOrMoreThanTwoPortionsOfDoughPerDay,
        ],
        [
          l10n.txtTwoTeacups,
          l10n.txtOneTeacupDaily,
          l10n.txtLessThanOneTeacupDaily,
        ],
        [
          l10n.txtOnePortionTheSizeOfSmallMatchboxOrHalfTheSizeOfSUBECardOrTwoTableSpoonsDaily,
          l10n.txtOnePortionTheSizeOfDiceOrOneTableSpoonDaily,
          l10n.txtLessThanOnePortionSizeDiceOrLessThanOneTbspDaily,
        ],
        [
          l10n.txtOneSmallPortionWithoutWasteBeefPlusEggDaily,
          l10n.txtTwoSmallPortionsWithoutWasteDailyOrUpToFourEggUnitsDailyOrOneSmallPortionPlusTwoEggUnits,
          l10n.txtMoreThanTwoSmallPortionsWithoutWasteDailyOrMoreThanFourEggUnitsDailyOrMoreThanOneSmallPortionPlusTwoEggUnits,
        ],
        [
          l10n.txtTwoMediumPortionsOrTwoCansPerWeek,
          l10n.txtOneMediumPortionOrOneCanPerWeek,
          l10n.txtLessThanOneMediumPortionOrLessThanOneCanPerWeek,
        ],
        [
          l10n.txtEightWalnutHalvesOrFifteenAlmondsOrTwoDessertTableSpoonsOfSeedsOrPeanutsPerDay,
          l10n.txtFourWalnutHalvesOrEightAlmondsOrOneTableSpoonDailyOfSeedsOrPeanuts,
          l10n.txtLessThanFourWalnutHalvesOrLessThanEightAlmondsOrLessThanOneTableSpoonDailyOfSeedsOrPeanuts,
        ],
        [
          l10n.txtTwoTableSpoonsDaily,
          l10n.txtOneTableSpoonDaily,
          l10n.txtLessThanOneTableSpoonDaily,
        ],
      ],
// 14 a 18 años
      [
        [
          l10n.txtOneAndHalfDishPerWeek,
          l10n.txtOneDishPerWeek,
          l10n.txtLessThanOneDishPerWeek,
        ],
        [
          l10n.txtFiveDishesPerWeek,
          l10n.txtThreeDishesPerWeek,
          l10n.txtLessThanThreeDishesPerWeek,
        ],
        [
          l10n.txtOneAndHalfDishPerWeekOrOneDishPlusOneMedallionPerWeek,
          l10n.txtOneDishPerWeekOrHalfDishPlusOneMedallionPerWeek,
          l10n.txtLessThanOneDishPerWeekOrHalfDishPlusOneMedallionPerWeek,
        ],
        [
          l10n.txtHalfDishDailyOrUpToFiveSmallUnitsPerWeek,
          l10n.txtThreeQuartersDishDailyOrSmallUnitEveryDay,
          l10n.txtMoreThanThreeQuartersDishDailyOrSmallUnitEveryDay,
        ],
        [
          l10n.txtFiveMediumUnitsPerWeekOrHalfRawDishDailyOrQuarterCookedDishDaily,
          l10n.txtTwoAndHalfMediumUnitsPerWeekOrOneThirdRawDishDailyOrQuarterCookedDish,
          l10n.txtLessThanTwoAndHalfMediumUnitsPerWeekOrLessThanOneThirdRawDishDailyOrLessThanQuarterCookedDish,
        ],
        [
          l10n.txtOneAndHalfLargeUnitPerDayOrTwoMediumUnitsPerDay,
          l10n.txtOneMediumUnitPerDay,
          l10n.txtLessThanOneMediumUnitPerDay,
        ],
        [
          l10n.txtUpToTwoSlicesOfBreadPerDayOrTwoSmallMignonsOrSixWaterBiscuits,
          l10n.txtThreeSlicesOfBreadPerDayOrThreeSmallMignonsOrNineWaterBiscuits,
          l10n.txtMoreThanThreeSlicesOfBreadPerDayOrMoreThanThreeSmallMignonsOrMoreThanNineWaterBiscuits,
        ],
        [
          l10n.txtHalfDishOfPastaPerDayOrTwoServingsOfDoughPerDay,
          l10n.txtThreeQuartersDishPerDayOrTwoServingsOfDoughPerDay,
          l10n.txtMoreThanThreeQuartersDishPerDayOrMoreThanTwoServingsPerDay,
        ],
        [
          l10n.txtHalfDishPerDayOrTwoServingsOfDoughPerDay,
          l10n.txtThreeQuartersDishPerDayOrThreeServingsOfDoughPerDay,
          l10n.txtMoreThanThreeQuartersDishPerDayOrMoreThanThreeServingsOfDoughPerDay,
        ],
        [
          l10n.txtTwoBreakfastCupSizeDaily,
          l10n.txtOneBreakfastCupSizeDaily,
          l10n.txtLessThanOneBreakfastCupSizeDaily,
        ],
        [
          l10n.txtOnePortionTheSizeOfSmallMatchboxOrHalfSUBECardOrTwoTableSpoonsDaily,
          l10n.txtOnePortionTheSizeOfDiceOrOneTableSpoonDaily,
          l10n.txtLessThanOnePortionSizeDiceOrLessThanOneTbspDaily, 
        ],
        [
          l10n.txtOneSmallPortionWithoutWasteDailyOrUpToTwoEggUnitsOrHalfSmallPortionPlusOneEgg,
          l10n.txtTwoSmallPortionsWithoutWasteDailyOrUpToFourEggUnitsDailyOrOneSmallPortionPlusTwoEggUnits,
          l10n.txtMoreThanTwoSmallPortionsWithoutWasteDailyOrMoreThanFourEggUnitsDailyOrMoreThanOneSmallPortionPlusTwoEggUnits,
        ],
        [
          l10n.txtTwoMediumPortionsOrTwoCansPerWeek,
          l10n.txtOneMediumPortionOrOneCanPerWeek,
          l10n.txtLessThanOneMediumPortionOrLessThanOneCanPerWeek,
        ],
        [
          l10n.txtTenWalnutHalvesOrTwentyAlmondsOrTwoDessertTableSpoonsOfSeedsOrPeanutsPerDay,
          l10n.txtFiveWalnutHalvesOrTenAlmondsOrOneTableSpoonDailyOfSeedsOrPeanuts,
          l10n.txtLessThanFiveWalnutHalvesOrLessThanTenAlmondsOrLessThanOneTableSpoonDailyOfSeedsOrPeanuts,
        ],
        [
          l10n.txtTwoTableSpoonsPerDay,
          l10n.txtOneTableSpoonPerDay,
          l10n.txtLessThanOneTableSpoonPerDay,
        ],
      ],
    ], // Fin femenino
// Masculino
    [
// De 5 a 8 años
      [
        [
          l10n.txtOnePlatePerWeek,
          l10n.txtHalfPlatePerWeek,
          l10n.txtLessThanHalfPlatePerWeek,
        ],
        [
          l10n.txtThreePlatesPerWeekOrOneSmallUnitPerDay,
          l10n.txtOneAndHalfPlatesPerWeekOrOneSmallUnitEveryOtherDay,
          l10n.txtLessThanOneAndHalfPlatesPerWeekOrLessThanOneSmallUnitEveryOtherDay,
        ],
        [
          l10n.txtHalfPlatePerWeekOrQuarterPlatePlusOneMedallionPerWeek,
          l10n.txtQuarterPlatePerWeekOrOneSmallMedallionPerWeek,
          l10n.txtLessThanQuarterPlatePerWeekOrLessThanOneSmallMedallionPerWeek,
        ],
        [
          l10n.txtHalfSmallUnitPerDayOrQuarterPlatePerDayOrThreeSmallUnitsPerWeek,
          l10n.txtOneSmallUnitPerDayOrHalfPlatePerDayOrThreeMediumUnitsPerWeek,
          l10n.txtMoreThanOneSmallUnitPerDayOrMoreThanHalfPlatePerDayOrMoreThanThreeMediumUnitsPerWeek,
        ],
        [
          l10n.txtThreeMediumUnitsPerWeekOrOneThirdRawPlateOrQuarterCookedPlate,
          l10n.txtOneMediumUnitPerWeekOrQuarterRawPlatePerDayOrQuarterPlateFourTimesPerWeek,
          l10n.txtLessThanOneMediumUnitPerWeekOrQuarterRawPlatePerDayOrQuarterPlateFourTimesPerWeek,
        ],
        [
          l10n.txtTwoMediumUnitsPerDay,
          l10n.txtOneMediumUnitPerDay,
          l10n.txtLessThanOneMediumUnitPerDay,
        ],
        [
          l10n.txtUpToOneSlicePerDayOrOneSmallMignonPerDay,
          l10n.txtTwoSlicesPerDayOrTwoSmallMignonsPerDay,
          l10n.txtMoreThanTwoSlicesPerDayOrMoreThanTwoSmallMignonsPerDay,
        ],
        [
          l10n.txtQuarterPlatePerDayOfWholeWheatPastaOrOneServingOfDoughPerDay,
          l10n.txtHalfPlatePerDayOrTwoServingsOfDoughPerDay,
          l10n.txtMoreThanHalfPlatePerDayOrMoreThanTwoServingsPerDay,
        ],
        [
          l10n.txtQuarterPlatePerDayOfWholeWheatPastaOrOneServingOfDoughPerDay,
          l10n.txtHalfPlatePerDayOrTwoServingsOfDoughPerDay,
          l10n.txtMoreThanHalfPlatePerDayOrMoreThanTwoServingsPerDay,
        ],
        [
          l10n.txtThreeQuartersCupForBreakfastDailyOrTwoTeaCupsDaily,
          l10n.txtHalfCupForBreakfastOrOneTeaCupDaily,
          l10n.txtLessThanHalfCupForBreakfastOrLessThanOneTeaCup,
        ],
        [
          l10n.txtOnePortionTheSizeOfSmallMatchboxOrHalfSUBECardOrTwoTableSpoons,
          l10n.txtOnePortionTheSizeOfADie,
          l10n.txtLessThanOnePortionTheSizeOfADie,
        ],
        [
          l10n.txtOneSmallPortionWithoutWasteFiveTimesPerWeekOrHalfSmallPortionPlusOneEggDaily,
          l10n.txtOneMediumPortionWithoutWasteDailyOrOneSmallPortionPlusOneEggDaily,
          l10n.txtMoreThanOneMediumPortionWithoutWasteDailyOrMoreThanOneSmallPortionPlusOneEggDaily,
        ],
        [
          l10n.txtTwoSmallPortionsPerWeekOrOneAndHalfCansPerWeek,
          l10n.txtOneSmallPortionPerWeekOrOneCanPerWeek,
          l10n.txtLessThanOneSmallPortionPerWeekOrLessThanOneCanPerWeek,
        ],
        [
          l10n.txtSixWalnutHalvesOrTenAlmondsOrOneTableSpoonDailyOfSeedsOrPeanuts,
          l10n.txtThreeWalnutHalvesOrFiveAlmondsOrHalfTableSpoonDailyOfSeedsOrPeanuts,
          l10n.txtLessThanThreeWalnutHalvesOrLessThanFiveAlmondsOrLessThanHalfTableSpoonDailyOfSeedsOrPeanuts,
        ],
        [
          l10n.txtTwoDessertSpoonsPerDay,
          l10n.txtOneDessertSpoonPerDay,
          l10n.txtLessThanOneDessertSpoonPerDay,
        ],
      ], // End of 5 to 8 years
// From 9 to 14 years
      [
        [
          l10n.txtOneAndHalfPlatesPerWeek,
          l10n.txtOnePlatePerWeek,
          l10n.txtLessThanOnePlatePerWeek,
        ],
        [
          l10n.txtFiveAndHalfPlatesPerWeekOrOneMediumUnitPerDayOrThreeQuartersPlatePerDay,
          l10n.txtThreePlatesPerWeekOrOneSmallUnitPerDayOrOneThirdPlatePerDay,
          l10n.txtLessThanThreePlatesPerWeekOrLessThanOneDailyUnitOrLessThanOneThirdPlatePerDay,
        ],
        [
          l10n.txtOneAndHalfPlatesPerWeekOrHalfPlateThreeTimesPerWeekOrOneMedallionPerDay,
          l10n.txtOnePlatePerWeekOrHalfPlatePerWeekOrOneMedallionThreeTimesPerWeek,
          l10n.txtLessThanOnePlatePerWeekOrLessThanHalfPlatePerWeekOrLessThanOneMedallionThreeTimesPerWeek,
        ],
        [
          l10n.txtOneSmallUnitPerDayOrThreeMediumUnitsPerWeekOrOneThirdPlatePerDay,
          l10n.txtOneMediumUnitPerDayOrThreeLargeUnitsPerWeekOrThreeQuartersPlatePerDay,
          l10n.txtMoreThanOneMediumUnitPerDayOrMoreThanThreeLargeUnitsPerWeekOrMoreThanThreeQuartersPlatePerDay,
        ],
        [
          l10n.txtFiveMediumUnitsPerWeekOrHalfRawPlateDailyOrQuarterCookedPlateDaily,
          l10n.txtTwoAndHalfMedUnitsWkThirdRawFourthCookedPlateDS,
          l10n.txtLessThanTwoAndHalfMedUnitsWkThirdRawFourthCookedPlateDS,
        ],
        [
          l10n.txtOneAndHalfLargeUnitPerDayOrTwoMediumUnitsPerDayOrThreeSmallUnits,
          l10n.txtOneMediumUnitPerDayOrTwoSmallUnits,
          l10n.txtLessThanOneMediumUnitPerDayOrLessThanTwoSmallUnitsPerDay,
        ],
        [
          l10n.txtUpToTwoMoldTypeSlicesPerDayOrTwoSmallMignonsPerDay,
          l10n.txtThreeMoldTypeSlicesPerDayOrThreeSmallMignonsPerDay,
          l10n.txtMoreThanThreeMoldTypeSlicesPerDayOrMoreThanThreeSmallMignonsPerDay,
        ],
        [
          l10n.txtQuarterPlateOfWholeWheatPastaPerDayOrOneServingOfDough,
          l10n.txtHalfPlatePerDayOrTwoServingsOfDoughPerDay,
          l10n.txtMoreThanHalfPlatePerDayOrMoreThanTwoServingsPerDay,
        ],
        [
          l10n.txtQuarterPlateOfWholeWheatPastaPerDayOrOneServingOfDough,
          l10n.txtHalfPlatePerDayOrTwoServingsOfDoughPerDay,
          l10n.txtMoreThanHalfPlatePerDayOrMoreThanTwoServingsPerDay,
        ],
        [
          l10n.txtTwoBreakfastTypeCups,
          l10n.txtOneBreakfastTypeCup,
          l10n.txtLessThanOneBreakfastTypeCup,
        ],
        [
          l10n.txtOneSmallMatchboxSizePortionOrHalfSUBECardOrTwoTableSpoonsDaily,
          l10n.txtOneDiceSizePortionOrOneTableSpoonDaily,
          l10n.txtLessThanOneDiceSizePortionOrLessThanOneTableSpoonDaily,
        ],
        [
          l10n.txtOneSmallPortionWithoutWasteDailyOrUpToTwoEggUnitsDailyOrOneSliceSizePortionOfPecetoPlusOneEggDaily,
          l10n.txtTwoSmallPortionsWithoutWasteDailyOrUpToFourEggUnitsDailyOrOneSmallPortionPlusTwoEggUnitsDaily,
          l10n.txtMoreThanTwoSmallPortionsWithoutWasteDailyOrMoreThanFourEggUnitsDailyOrMoreThanOneSmallPortionPlusTwoEggUnitsDaily,
        ],
        [
          l10n.txtTwoMediumPortionsOrTwoCansPerWeek,
          l10n.txtOneMediumPortionOrOneCanPerWeek,
          l10n.txtLessThanOneMediumPortionOrLessThanOneCanPerWeek,
        ],
        [
          l10n.txtTenWalnutHalvesOrTwentyAlmondsOrTwoTableSpoonsDailyOfSeedsOrPeanuts,
          l10n.txtFiveWalnutHalvesOrTenAlmondsOrOneTableSpoonDailyOfSeedsOrPeanuts,
          l10n.txtLessThanFiveWalnutHalvesOrLessThanTenAlmondsOrLessThanOneTableSpoonDailyOfSeedsOrPeanuts,
        ],
        [
          l10n.txtTwoTableSpoonsDaily,
          l10n.txtOneTableSpoonDaily,
          l10n.txtLessThanOneTableSpoonDaily,
        ]
      ], // Fin de 9 a 14 años
// De 15 a 18 años
      [
        [
          l10n.txtTwoPlatesPerWeek,
          l10n.txtOnePlatePerWeek,
          l10n.txtLessThanOnePlatePerWeek,
        ],
        [
          l10n.txtHalfPlateCookedDailyOrThreeQuartersPlateRawDailyOrSixMediumUnitsPerWeek,
          l10n.txtQuarterPlateCookedDailyOrHalfPlateRawDailyOrThreeMediumUnitsPerWeek,
          l10n.txtLessThanQuarterPlateCookedDailyOrLessThanHalfPlateRawDailyOrLessThanThreeMediumUnitsPerWeek,
        ],
        [
          l10n.txtTwoPlatesPerWeekOrOnePlatePlusTwoMedallionsPerWeek,
          l10n.txtOnePlatePerWeekOrHalfPlatePlusOneMedallionPerWeek,
          l10n.txtLessThanOnePlatePerWeekOrLessThanHalfPlatePlusOneMedallionPerWeek,
        ],
        [
          l10n.txtUpToSixSmallUnitsPerWeekOrThreeLargeUnitsPerWeekOrHalfPlateDaily,
          l10n.txtUpToNineUnitsPerWeekOrFiveLargeUnitsPerWeekOrOnePlateDaily,
          l10n.txtMoreThanNineUnitsWkFiveLargeOnePlateDailyDS,
        ],
        [
          l10n.txtOneMediumUnitDailyOrThreeQuartersPlateRawDailyOrHalfPlateCookedDaily,
          l10n.txtOneSmallUnitDailyOrHalfPlateRawDailyOrQuarterPlateCookedDaily,
          l10n.txtLessThanOneSmallUnitDailyOrLessThanHalfPlateRawDailyOrLessThanQuarterPlateCookedDaily,
        ],
        [
          l10n.txtTwoLargeUnitsPerDayOrFourSmallUnitsPerDay,
          l10n.txtOneLargeUnitPerDayOrTwoSmallUnitsPerDay,
          l10n.txtLessThanOneLargeUnitPerDayOrLessThanTwoSmallUnitsPerDay,
        ],
        [
          l10n.txtThreeSlicesPerDayOrTwoSmallMedallions,
          l10n.txtSixSlicesPerDayOrFourSmallMedallionsOrTwoSmallFlutes,
          l10n.txtMoreThanSixSlicesPerDayOrMoreThanFourSmallMedallionsOrMoreThanTwoSmallFlutes,
        ],
        [
          l10n.txtHalfPlateOfWholeWheatPastaPerDayOrOneAndHalfPortionOfDoughPerDay,
          l10n.txtOnePlatePerDayOrThreePortionsOfDoughPerDay,
          l10n.txtMoreThanOnePlatePerDayOrMoreThanThreePortionsOfDoughPerDay,
        ],
        [
          l10n.txtHalfPlateOfWholeWheatPastaPerDayOrOneAndHalfPortionOfDoughPerDay,
          l10n.txtOnePlatePerDayOrThreePortionsOfDoughPerDay,
          l10n.txtMoreThanOnePlatePerDayOrMoreThanThreePortionsOfDoughPerDay,
        ],
        [
          l10n.txtTwoBreakfastCups,
          l10n.txtOneBreakfastCup,
          l10n.txtLessThanOneBreakfastCup,
        ],
        [
          l10n.txtOnePortionTheSizeOfSmallMatchboxOrHalfSUBECardOrTwoTableSpoons,
          l10n.txtOnePortionTheSizeOfADiceOrOneTableSpoon,
          l10n.txtLessThanOnePortionTheSizeOfADiceOrLessThanOneTableSpoon,
        ],
        [
          l10n.txtOneMediumPortionWithoutWasteDailyOrUpToThreeEggsDailyOrOneSmallPortionPlusTwoEggsDaily,
          l10n.txtTwoSmallPortionsWithoutWasteDailyOrUpToFourEggsOrOneMediumPortionPlusTwoEggs,
          l10n.txtMoreThanTwoSmallPortionsWithoutWasteDailyOrUpToFourEggsDailyOrMoreThanOneMediumPortionPlusTwoEggs,
        ],
        [
          l10n.txtTwoLargePortionsPerWeekOrTwoCansPerWeekOrOneThirdPlateOfCannedFishPerWeek,
          l10n.txtOneMediumPortionPerWeekOrOneCanPerWeekOrQuarterPlatePerWeek,
          l10n.txtLessThanOneMediumPortionPerWeekOrLessThanOneCanPerWeekOrLessThanQuarterPlatePerWeek,
        ],
        [
          l10n.txtTenWalnutHalvesPerDayOrTwentyAlmondsPerDayOrTwoTableSpoonsPerDayOfSeedsOrPeanuts,
          l10n.txtFiveWalnutHalvesPerDayOrTenAlmondsPerDayOrOneTableSpoonPerDayOfSeedsOrPeanuts,
          l10n.txtLessThanFiveWalnutHalvesPerDayOrLessThanTenAlmondsPerDayOrLessThanOneTableSpoonPerDayOfSeedsOrPeanuts,
        ],
        [
          l10n.txtThreeTableSpoonsPerDay,
          l10n.txtOneTableSpoonPerDay,
          l10n.txtLessThanOneTableSpoonPerDay,
        ]
      ],
    ]
  ];
}
